### ISSUE TITLE
Execution as a non-privileged user with no system configuration

### ISSUE THREAD

**Issue by brainfunked** [gluster/gadmin#6]
When gadmin is run by a non-privileged user, the following needs to happen:

* Check if `$GADMIN_HOME` is set. If yes:
  * Inform the user that it is set and that its value will be used as the work directory.
  * Check if the directory is writable. If not, inform the user and exit.
* If `$GADMIN_HOME` is not set, inform the user and exit.

**Comment by sac** [comment]
We can default to /var/lib/gadmin and if user wants a different directory he can then set GADMIN_HOME

**Comment by brainfunked** [comment]
Defaulting to a system path is a bad practice IMO. A practice I follow from my experience of writing and running ruby apps and working with a bunch of python apps (which default to system directories); is to ensure that an application that is not intended to be run with root privileges should default to a local directory writable by the current user. In ruby apps, this enabled running of the application from the git checkout and easy deployments by wiring up the application using symlinks on a deployment system. Correspondingly, I've been extremely frustrated at python applications defaulting to system directories that prevents them from running on my local setup.

In case of gadmin, given the way go workspaces are setup, the ruby approach doesn't make sense because go applications are installed in a "shared" workspace where all other go stuff lives. This prevents defaulting to the application's installation directory. Using `$CWD` is always a bad idea since the user doesn't expect the application to pollute the current working directory and is badly surprised when that happens. For gadmin, the runtime/work directory is a necessity. It is better to force the user to provide informed, explicit configuration for this.

Also, the defaulting to the system directory with the proper user etc. would automatically be achieved when deployed via RPM. This is being addressed in #5.

**Comment by brainfunked** [comment]
The current implementation actually betrays the principal I've stated in my previous comment; that of not surprising the user. Presently, when `$GADMIN_HOME` is set to a relative path, it is being turned into an absolute path based on `$CWD` and used. In most cases where the relative path is not intended but provided erroneously, gadmin will fail to run since the directory won't exist. However, in accordance with the principal stated earlier, gadmin should mandate an absolute path via `$GADMIN_HOME`.
